project:
  type: website

website:
  title: modelling-marti
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://mtwente.github.io/modelling-marti/
  repo-url: https://github.com/mtwente/modelling-marti/
  issue-url: https://github.com/mtwente/modelling-marti/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: modelling-marti
    tools:
      - icon: github
        url: https://github.com/mtwente/modelling-marti/
    left:
      - text: Readme
        href: index.qmd
      - text: Analysis
        href: report/index.qmd
      - text: Data
        href: docs/data.qmd

  sidebar:
    contents:
      - section: modelling-marti
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md

format:
  html:
    toc: true
    theme: cosmo
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    mainfont: Jost
    css: styles.css
    mermaid:
      theme: neutral
    filters: [pandoc-quotes.lua]
    quot-lang: de-CH
    other-links:
      - text: 'Publikationen von Hans Marti (Zotero)'
        icon: book
        href: https://www.zotero.org/groups/5722431/hansmarti-publications/library
      - text: 'Nachlass von Hans Marti im gta Archiv'
        icon: archive
        href: https://archiv.gta.arch.ethz.ch/de/katalog?collections=757353
      - text: 'Schweizerische Geschichtstage 2025'
        icon: people-fill
        href: https://mtwente.github.io/geschichtstage25

freeze: true

editor: source
